### PR TITLE
Temitope fe

### PR DESCRIPTION
**Pull request by Temitope15**
# *Pull Request Template*

## Description (*What does this PR do?*)
Create upload content for the book upload form
Please provide a brief description of the changes introduced by this pull request.
I updated the upload books page to display inputs to upload books

## Related Issue(s)

- [x] [issue 1](https://trello.com/c/tjxrMWUs/24-upload-book-page#)

## Checklist

- [x] I have tested the changes locally and they work as expected.
- [x] The code follows the project's coding standards and conventions.
- [x] I have added appropriate comments and documentation where necessary.
- [x] All tests passed successfully.
- [x] I have updated the necessary dependencies.
- [x] I ran ``` npm run build ``` and it built without errors

## Changes Made
 - removed the content that was there before
 - added the inputs as required by the figma design
 - created reusable components inside src/components/uploadContents.jsx  and used them in the file.

## Screenshots

Ensure you add screenshots or GIFs to showcase the changes visually.

localhost_5173_uploads(Nest Hub)

## Additional Notes

Add any additional notes or context that may be helpful for the reviewer.

 - I think there should be a submit button added to the figma file so as to submit the inputs given. Also, the upload sidebar should be hidden when it is in mobile view, review on that can be made too.

### CODE REVIEW

**Comment by Christiano112** [comment]
the sideNav should always span the full height of the screen.

alternate 100% and 100vh for the height to see which gives what is needed

**Review by Christiano112 — CHANGES_REQUESTED** [review]
fix the sideNav height

**Comment by Temitope15** [comment]
Okay

**Comment by Temitope15** [comment]
The sidebar is actually fixed based on what has been styled in the component. The reason it looks like that is because I snapped it using the nest-hub view. But on normal laptop i.e in the browser, it is fixed.

**Comment by Temitope15** [comment]
I think the fix is to just work on the responsiveness, i.e hide the sidebar on Mobile screens and when we click a toggle is shows like a nav menu would show on a mobile.

**Pull request merged**
